[tool.poetry]
authors = [
  "Joel Lee <joel@joellee.org>",
  "Leon Fedden <leonfedden@gmail.com>",
  "Daniel Reinón García <danielreinon@outlook.com>",
  "Leynier Gutiérrez González <leynier41@gmail.com>",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
description = "Supabase Storage client for Python."
documentation = "https://github.com/supabase-community/storage-py"
homepage = "https://github.com/supabase-community/storage-py"
license = "MIT"
name = "storage3"
readme = "README.md"
repository = "https://github.com/supabase-community/storage-py"
version = "0.2.0"

[tool.poetry.dependencies]
httpx = ">=0.19,<0.22"
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
commitizen = "^2.20.3"
flake8 = "^4.0.1"
isort = "^5.9.3"
pre-commit = "^2.16.0"
pytest = "^6.2.5"
pytest-asyncio = "^0.18.3"
pytest-cov = "^3.0.0"
python-dotenv = "^0.20.0"
unasync-cli = "^0.0.9"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version = "0.1.0"
version_files = [
  "storage3/utils.py",
  "pyproject.toml:version",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
